use std::fs::File;
use std::io::{BufReader, BufWriter, Read, Write};
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use chrono::Utc;
use protocol::repository_scope_for_path;
use serde::{Deserialize, Serialize};
use tar::{Archive, Builder, EntryType, Header};

use crate::cli_types::{StateCommand, StateExportArgs, StateImportArgs};
use crate::{conflict_error, internal_error, invalid_input_error, not_found_error, print_value};

const EXPORT_SCHEMA_V1: &str = "animus.state.export.v1";
const MANIFEST_FILENAME: &str = "MANIFEST.json";
const PRINCIPALS_ARCHIVE_PATH: &str = "global/principals.yaml";
const SCOPE_ARCHIVE_PREFIX: &str = "scope/";
const ZSTD_LEVEL: i32 = 3;

/// Files inside `daemon/` that are pure runtime state (locks, logs,
/// pid files, sockets). They are excluded from the default export
/// scope so a restore on a different machine doesn't fight with the
/// running daemon. The user can still capture the full scope by
/// archiving manually if they really want to.
const DAEMON_RUNTIME_FILES: &[&str] = &["daemon.lock", "daemon.log", "daemon.pid", "control.sock"];

/// Top-level entries in the scope dir we exclude from the default
/// export. These are either ephemeral runtime artifacts (sockets,
/// lock files, log streams) or directories handled by their own
/// opt-in flags (`runs/`, `artifacts/`).
const SCOPE_TOPLEVEL_EXCLUDES: &[&str] = &[
    "control.sock",
    "core-state.lock",
    "daemon",
    "config",
    "runs",
    "artifacts",
    "worktrees",
    // Bootstrap markers: `.project-root` carries the user's absolute
    // source path (useless / wrong on another machine and in a
    // re-scope) and `.git-origin` carries the raw remote URL, which
    // can embed a `token@host` credential. Both are regenerated by
    // the runtime on next access; skipping them in the archive keeps
    // backups portable AND avoids leaking credentials via the
    // remote-URL form.
    ".project-root",
    ".git-origin",
];

/// File-extension blocklist for top-level scope files. Picks up lock /
/// socket / pid files we'd otherwise capture by accident.
const SCOPE_TOPLEVEL_EXCLUDE_EXTENSIONS: &[&str] = &["lock", "sock", "pid"];

/// Tokens that look like secrets when they appear as JSON keys. If a
/// state JSON file carries any of these we refuse the export — secrets
/// belong in a per-machine keychain, not a portable backup archive.
const SECRET_KEY_TOKENS: &[&str] = &["token", "secret", "api_key", "apikey", "password", "passphrase", "credential"];

#[derive(Debug, Serialize, Deserialize)]
struct Manifest {
    schema: String,
    exported_at: String,
    animus_version: String,
    repo_scope: String,
    include_runs: bool,
    include_artifacts: bool,
    file_count: u64,
    total_bytes_uncompressed: u64,
}

#[derive(Debug, Serialize)]
struct ExportResult {
    schema: &'static str,
    archive: PathBuf,
    repo_scope: String,
    file_count: u64,
    total_bytes_uncompressed: u64,
    include_runs: bool,
    include_artifacts: bool,
    principals_yaml_included: bool,
}

#[derive(Debug, Serialize)]
struct ImportResult {
    schema: &'static str,
    archive: PathBuf,
    target_scope_dir: PathBuf,
    repo_scope_source: String,
    repo_scope_target: String,
    file_count: u64,
    snapshot_dir: Option<PathBuf>,
    principals_overwritten: bool,
}

pub(crate) async fn handle_state(command: StateCommand, project_root: &str, json: bool) -> Result<()> {
    match command {
        StateCommand::Export(args) => handle_export(args, project_root, json),
        StateCommand::Import(args) => handle_import(args, project_root, json),
    }
}

fn handle_export(args: StateExportArgs, project_root: &str, json: bool) -> Result<()> {
    let project_root_path = Path::new(project_root);
    // Resolve the scope dir WITHOUT mutating disk. `scoped_state_root`
    // would create the dir + marker files on a fresh project and let
    // us emit a marker-only archive — exactly the empty-state case we
    // want to refuse. Use a read-only lookup that prefers a same-origin
    // adopted scope when available.
    let (scope, scope_dir) = resolve_existing_scope_dir(project_root_path);
    if !scope_dir.exists() || !scope_dir_has_real_state(&scope_dir) {
        return Err(not_found_error(format!(
            "no scoped state at {} — nothing to export. Run an Animus command in this project first.",
            scope_dir.display()
        )));
    }

    let exported_at = Utc::now();
    let out_path = match args.out {
        Some(path) => PathBuf::from(path),
        None => default_export_path(&scope, &exported_at),
    };

    if let Some(parent) = out_path.parent() {
        if !parent.as_os_str().is_empty() && !parent.exists() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("create parent dir for archive at {}", parent.display()))?;
        }
    }

    let entries = collect_export_entries(&scope_dir, args.include_runs, args.include_artifacts)?;
    scan_entries_for_secrets(&entries)?;

    let principals_path = principals_path();
    let principals_included = principals_path.exists();

    let mut total_bytes: u64 = 0;
    let mut file_count: u64 = 0;
    for entry in &entries {
        let meta =
            std::fs::metadata(&entry.source).with_context(|| format!("stat {} for export", entry.source.display()))?;
        if meta.is_file() {
            total_bytes += meta.len();
            file_count += 1;
        }
    }
    if principals_included {
        let meta = std::fs::metadata(&principals_path)
            .with_context(|| format!("stat principals.yaml at {}", principals_path.display()))?;
        total_bytes += meta.len();
        file_count += 1;
    }

    let manifest = Manifest {
        schema: EXPORT_SCHEMA_V1.to_string(),
        exported_at: exported_at.to_rfc3339(),
        animus_version: env!("CARGO_PKG_VERSION").to_string(),
        repo_scope: scope.clone(),
        include_runs: args.include_runs,
        include_artifacts: args.include_artifacts,
        file_count,
        total_bytes_uncompressed: total_bytes,
    };
    let manifest_bytes = serde_json::to_vec_pretty(&manifest).context("serialize MANIFEST.json")?;

    write_archive(&out_path, &manifest_bytes, &entries, principals_included.then_some(&principals_path))?;

    let result = ExportResult {
        schema: EXPORT_SCHEMA_V1,
        archive: out_path,
        repo_scope: scope,
        file_count,
        total_bytes_uncompressed: total_bytes,
        include_runs: args.include_runs,
        include_artifacts: args.include_artifacts,
        principals_yaml_included: principals_included,
    };
    print_value(result, json)
}

fn handle_import(args: StateImportArgs, project_root: &str, json: bool) -> Result<()> {
    let archive_path = PathBuf::from(&args.archive);
    if !archive_path.exists() {
        return Err(not_found_error(format!("archive not found at {}", archive_path.display())));
    }

    let manifest = read_manifest(&archive_path)?;
    if manifest.schema != EXPORT_SCHEMA_V1 {
        return Err(invalid_input_error(format!(
            "unsupported export schema {:?} — this animus build only loads {}; upgrade animus and retry",
            manifest.schema, EXPORT_SCHEMA_V1
        )));
    }

    let target_scope = match args.into_project.as_deref() {
        Some(path) => repository_scope_for_path(Path::new(path)),
        None => manifest.repo_scope.clone(),
    };
    // TODO(codex-p2): When `--into-project` differs from the source
    // scope, task records in the staged `core-state.json` can still
    // carry absolute `worktree_path` values rooted at the source
    // scope. The dispatcher rejects tasks whose recorded worktree
    // lives outside the target's managed worktree root, so imported
    // tasks become unrunnable until `animus subject status … --status
    // ready` clears the path. Rewriting these paths in-place during
    // re-scope is the right fix but requires plugin-state knowledge
    // we don't have at this layer — tracked for v0.5.9.
    // The manifest is untrusted. Validate before we let it influence
    // any path on disk so a crafted `repo_scope` like `../../escape`
    // can't make us write outside `~/.animus`.
    validate_scope_name(&target_scope)?;
    let _ = project_root;
    let target_scope_dir = scope_dir_for(&target_scope);
    let ao_root = animus_home()?;
    std::fs::create_dir_all(&ao_root).with_context(|| format!("create ao root at {}", ao_root.display()))?;

    let target_non_empty = scope_dir_is_nonempty(&target_scope_dir);
    if target_non_empty && !args.yes {
        return Err(conflict_error(format!(
            "target scope {} already has state; re-run with --yes to overwrite (a safety snapshot will be taken first)",
            target_scope_dir.display()
        )));
    }

    let timestamp = Utc::now().format("%Y%m%d%H%M%S").to_string();
    let staging_dir = ao_root.join(format!("{target_scope}.import-staging-{timestamp}"));
    if staging_dir.exists() {
        std::fs::remove_dir_all(&staging_dir)
            .with_context(|| format!("clear stale staging dir {}", staging_dir.display()))?;
    }
    std::fs::create_dir_all(&staging_dir).with_context(|| format!("create staging dir {}", staging_dir.display()))?;

    let extract =
        extract_archive(&archive_path, &staging_dir).context("extract archive into staging dir").inspect_err(|_| {
            let _ = std::fs::remove_dir_all(&staging_dir);
        })?;

    // Validate the staged payload BEFORE touching anything live —
    // neither the scope dir nor principals.yaml. A corrupt or empty
    // archive must never move the existing scope aside or write a new
    // RBAC root-of-trust just to fail seconds later.
    let staged_scope_payload = staging_dir.join("scope");
    if !staged_scope_payload.exists() {
        let _ = std::fs::remove_dir_all(&staging_dir);
        return Err(invalid_input_error(
            "archive does not contain a `scope/` payload — refusing to import an empty scope".to_string(),
        ));
    }
    let staged_meta = std::fs::symlink_metadata(&staged_scope_payload)
        .with_context(|| format!("stat staged scope payload at {}", staged_scope_payload.display()))?;
    if !staged_meta.file_type().is_dir() {
        let _ = std::fs::remove_dir_all(&staging_dir);
        return Err(conflict_error(format!(
            "staged scope payload at {} is not a directory — refusing import",
            staged_scope_payload.display()
        )));
    }
    // An empty `scope/` directory — or a directory tree with no real
    // files — shouldn't be allowed to clobber live state. Replacing a
    // non-empty scope with nothing is the worst possible failure mode
    // for a restore command, and an archive that only declares empty
    // subdirectories under `scope/` is functionally identical to one
    // with no payload at all.
    if !staged_scope_contains_file(&staged_scope_payload)? {
        let _ = std::fs::remove_dir_all(&staging_dir);
        return Err(invalid_input_error(
            "archive `scope/` directory contains no files — refusing to replace live state with empty payload"
                .to_string(),
        ));
    }

    // Plan the principals action up front. If we'd need
    // `--yes-overwrite-principals` and the user didn't pass it, refuse
    // NOW — before the live scope is moved. This is the load-bearing
    // safety property: a denied principals overwrite must never leave
    // the project with a half-restored scope.
    let principals_plan = plan_principals_action(&extract, args.yes_overwrite_principals).inspect_err(|_| {
        let _ = std::fs::remove_dir_all(&staging_dir);
    })?;

    let snapshot_dir = if target_non_empty {
        let snap = ao_root.join(format!("{target_scope}.backup-pre-import-{timestamp}"));
        std::fs::rename(&target_scope_dir, &snap).map_err(|err| {
            let _ = std::fs::remove_dir_all(&staging_dir);
            internal_error(format!("failed to snapshot existing scope to {}: {err}", snap.display()))
        })?;
        Some(snap)
    } else {
        if target_scope_dir.exists() {
            std::fs::remove_dir_all(&target_scope_dir).map_err(|err| {
                let _ = std::fs::remove_dir_all(&staging_dir);
                internal_error(format!("failed to clear empty scope dir {}: {err}", target_scope_dir.display()))
            })?;
        }
        None
    };

    if let Err(err) = std::fs::rename(&staged_scope_payload, &target_scope_dir) {
        // Best-effort rollback: put the snapshot back where the live
        // scope used to be so the project remains bootable. If this
        // rollback fails, surface both errors.
        if let Some(snap) = snapshot_dir.as_ref() {
            let _ = std::fs::rename(snap, &target_scope_dir);
        }
        let _ = std::fs::remove_dir_all(&staging_dir);
        return Err(internal_error(format!(
            "atomic swap failed (staging={}, target={}): {err}",
            staged_scope_payload.display(),
            target_scope_dir.display()
        )));
    }

    // Scope swap succeeded — only NOW touch principals.yaml. Any
    // failure here is from raw IO, not policy: the policy gate
    // (`plan_principals_action`) was checked before the swap.
    let principals_overwritten = apply_principals_action(&extract, principals_plan).inspect_err(|_| {
        let _ = std::fs::remove_dir_all(&staging_dir);
    })?;

    let _ = std::fs::remove_dir_all(&staging_dir);

    let result = ImportResult {
        schema: EXPORT_SCHEMA_V1,
        archive: archive_path,
        target_scope_dir,
        repo_scope_source: manifest.repo_scope,
        repo_scope_target: target_scope,
        file_count: manifest.file_count,
        snapshot_dir,
        principals_overwritten,
    };
    print_value(result, json)
}

struct ExportEntry {
    source: PathBuf,
    archive_relative: PathBuf,
}

fn collect_export_entries(scope_dir: &Path, include_runs: bool, include_artifacts: bool) -> Result<Vec<ExportEntry>> {
    let mut entries = Vec::new();
    let config_dir = scope_dir.join("config");
    if config_dir.is_dir() {
        walk_into(&config_dir, scope_dir, &mut entries, |_| true)?;
    }
    let daemon_dir = scope_dir.join("daemon");
    if daemon_dir.is_dir() {
        walk_into(&daemon_dir, scope_dir, &mut entries, |path| {
            let name = path.file_name().and_then(|n| n.to_str()).unwrap_or_default();
            !DAEMON_RUNTIME_FILES.contains(&name)
        })?;
    }

    // Top-level scope state outside config/ and daemon/: things like
    // `core-state.json`, `resume-config.json`, `workflow.db`,
    // `audit.jsonl`, `state/`, `docs/`, `metrics/`, `logs/`, plus the
    // migration / column marker files. These are the load-bearing
    // pieces of a restore — leaving them out makes the archive useless
    // for actual disaster recovery.
    let read = std::fs::read_dir(scope_dir).with_context(|| format!("read_dir {}", scope_dir.display()))?;
    for entry in read {
        let entry = entry.with_context(|| format!("read entry under {}", scope_dir.display()))?;
        let path = entry.path();
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or_default().to_string();
        if SCOPE_TOPLEVEL_EXCLUDES.contains(&name.as_str()) {
            continue;
        }
        if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
            if SCOPE_TOPLEVEL_EXCLUDE_EXTENSIONS.contains(&ext) {
                continue;
            }
        }
        let ft = entry.file_type().with_context(|| format!("stat {}", path.display()))?;
        if ft.is_symlink() {
            continue;
        }
        if ft.is_dir() {
            walk_into(&path, scope_dir, &mut entries, |_| true)?;
        } else if ft.is_file() {
            let rel = path
                .strip_prefix(scope_dir)
                .map(|p| p.to_path_buf())
                .with_context(|| format!("strip prefix {} from {}", scope_dir.display(), path.display()))?;
            entries.push(ExportEntry { source: path, archive_relative: rel });
        }
    }

    if include_runs {
        let runs_dir = scope_dir.join("runs");
        if runs_dir.is_dir() {
            walk_into(&runs_dir, scope_dir, &mut entries, |_| true)?;
        }
    }
    if include_artifacts {
        let artifacts_dir = scope_dir.join("artifacts");
        if artifacts_dir.is_dir() {
            walk_into(&artifacts_dir, scope_dir, &mut entries, |_| true)?;
        }
    }
    Ok(entries)
}

fn walk_into(
    root: &Path,
    scope_dir: &Path,
    out: &mut Vec<ExportEntry>,
    keep: impl Fn(&Path) -> bool + Copy,
) -> Result<()> {
    let read = std::fs::read_dir(root).with_context(|| format!("read_dir {}", root.display()))?;
    for entry in read {
        let entry = entry.with_context(|| format!("read entry under {}", root.display()))?;
        let path = entry.path();
        if !keep(&path) {
            continue;
        }
        let ft = entry.file_type().with_context(|| format!("stat {}", path.display()))?;
        if ft.is_symlink() {
            continue;
        }
        if ft.is_dir() {
            walk_into(&path, scope_dir, out, keep)?;
        } else if ft.is_file() {
            let rel = path
                .strip_prefix(scope_dir)
                .map(|p| p.to_path_buf())
                .with_context(|| format!("strip prefix {} from {}", scope_dir.display(), path.display()))?;
            out.push(ExportEntry { source: path, archive_relative: rel });
        }
    }
    Ok(())
}

fn scan_entries_for_secrets(entries: &[ExportEntry]) -> Result<()> {
    for entry in entries {
        let name = entry.source.file_name().and_then(|n| n.to_str()).unwrap_or_default();
        if name.eq_ignore_ascii_case(".env") || name.starts_with(".env.") {
            return Err(conflict_error(format!(
                "refusing to export likely secret file {} — move it outside the scope dir or scrub it first",
                entry.source.display()
            )));
        }
        if entry.source.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let bytes = match std::fs::read(&entry.source) {
            Ok(b) => b,
            Err(_) => continue,
        };
        let value: serde_json::Value = match serde_json::from_slice(&bytes) {
            Ok(v) => v,
            Err(_) => continue,
        };
        if let Some(hit) = find_secret_key(&value) {
            return Err(conflict_error(format!(
                "refusing to export {}: contains key {:?} that looks like a secret. Scrub the field or move credentials to a keychain plugin.",
                entry.source.display(),
                hit
            )));
        }
    }
    Ok(())
}

fn find_secret_key(value: &serde_json::Value) -> Option<String> {
    match value {
        serde_json::Value::Object(map) => {
            for (k, v) in map {
                if looks_like_secret_field(k, v) {
                    return Some(k.clone());
                }
                if let Some(hit) = find_secret_key(v) {
                    return Some(hit);
                }
            }
            None
        }
        serde_json::Value::Array(items) => items.iter().find_map(find_secret_key),
        _ => None,
    }
}

/// A field is treated as a credential only when BOTH:
///   * the key name contains one of `SECRET_KEY_TOKENS` (after
///     lowercasing), AND
///   * the value is a non-empty string of plausible credential length.
///
/// This intentionally lets numeric counters slide through —
/// `cost-state.v1.json` carries `total_tokens: 42` that the previous
/// rule treated as a secret, blocking ordinary backups.
fn looks_like_secret_field(key: &str, value: &serde_json::Value) -> bool {
    let lower = key.to_ascii_lowercase();
    if !SECRET_KEY_TOKENS.iter().any(|tok| lower.contains(tok)) {
        return false;
    }
    let Some(s) = value.as_str() else {
        return false;
    };
    let trimmed = s.trim();
    if trimmed.is_empty() {
        return false;
    }
    // Credentials are typically opaque tokens — ≥12 chars and not a
    // bare integer. Short or numeric values are almost always counters
    // (`tokens_used: "12"`) or descriptive labels rather than secrets.
    if trimmed.len() < 12 {
        return false;
    }
    if trimmed.chars().all(|c| c.is_ascii_digit()) {
        return false;
    }
    true
}

fn write_archive(
    out_path: &Path,
    manifest_bytes: &[u8],
    entries: &[ExportEntry],
    principals: Option<&Path>,
) -> Result<()> {
    let tmp = with_suffix(out_path, ".partial");
    if tmp.exists() {
        std::fs::remove_file(&tmp).with_context(|| format!("remove stale tmp at {}", tmp.display()))?;
    }
    let file = File::create(&tmp).with_context(|| format!("create archive at {}", tmp.display()))?;
    let encoder =
        zstd::stream::write::Encoder::new(BufWriter::new(file), ZSTD_LEVEL).context("init zstd encoder")?.auto_finish();
    let mut builder = Builder::new(encoder);

    append_bytes(&mut builder, Path::new(MANIFEST_FILENAME), manifest_bytes)?;

    for entry in entries {
        let archive_path = PathBuf::from(SCOPE_ARCHIVE_PREFIX).join(&entry.archive_relative);
        append_file(&mut builder, &archive_path, &entry.source)?;
    }
    if let Some(principals) = principals {
        append_file(&mut builder, Path::new(PRINCIPALS_ARCHIVE_PATH), principals)?;
    }

    builder.finish().context("finalize tar")?;
    drop(builder);

    std::fs::rename(&tmp, out_path)
        .with_context(|| format!("atomically move archive into place at {}", out_path.display()))?;
    Ok(())
}

fn append_bytes<W: Write>(builder: &mut Builder<W>, archive_path: &Path, bytes: &[u8]) -> Result<()> {
    let mut header = Header::new_gnu();
    header.set_size(bytes.len() as u64);
    header.set_mode(0o644);
    header.set_entry_type(EntryType::Regular);
    header.set_mtime(Utc::now().timestamp().max(0) as u64);
    header.set_path(archive_path).with_context(|| format!("set tar entry path {}", archive_path.display()))?;
    header.set_cksum();
    builder.append(&header, bytes).with_context(|| format!("append tar entry {}", archive_path.display()))?;
    Ok(())
}

fn append_file<W: Write>(builder: &mut Builder<W>, archive_path: &Path, source: &Path) -> Result<()> {
    let meta = std::fs::metadata(source).with_context(|| format!("stat {}", source.display()))?;
    let mut header = Header::new_gnu();
    header.set_metadata(&meta);
    header.set_path(archive_path).with_context(|| format!("set tar entry path {}", archive_path.display()))?;
    header.set_cksum();
    let file = File::open(source).with_context(|| format!("open {}", source.display()))?;
    builder
        .append(&header, BufReader::new(file))
        .with_context(|| format!("append tar entry {}", archive_path.display()))?;
    Ok(())
}

fn read_manifest(archive_path: &Path) -> Result<Manifest> {
    let file = File::open(archive_path).with_context(|| format!("open archive at {}", archive_path.display()))?;
    let decoder = zstd::stream::read::Decoder::new(BufReader::new(file)).context("init zstd decoder")?;
    let mut archive = Archive::new(decoder);
    for entry in archive.entries().context("iterate tar entries")? {
        let mut entry = entry.context("read tar entry")?;
        let path = entry.path().context("decode entry path")?.into_owned();
        if path == Path::new(MANIFEST_FILENAME) {
            let mut buf = Vec::new();
            entry.read_to_end(&mut buf).context("read MANIFEST.json from archive")?;
            let manifest: Manifest = serde_json::from_slice(&buf).context("parse MANIFEST.json from archive")?;
            return Ok(manifest);
        }
    }
    Err(invalid_input_error(
        "archive is missing MANIFEST.json — not a valid animus.state.export.v1 archive".to_string(),
    ))
}

struct ExtractOutcome {
    staged_principals: Option<PathBuf>,
}

fn extract_archive(archive_path: &Path, staging_dir: &Path) -> Result<ExtractOutcome> {
    let file = File::open(archive_path).with_context(|| format!("open archive at {}", archive_path.display()))?;
    let decoder = zstd::stream::read::Decoder::new(BufReader::new(file)).context("init zstd decoder")?;
    let mut archive = Archive::new(decoder);
    let mut staged_principals = None;
    for entry in archive.entries().context("iterate tar entries")? {
        let mut entry = entry.context("read tar entry")?;
        let raw_path = entry.path().context("decode entry path")?.into_owned();
        if raw_path == Path::new(MANIFEST_FILENAME) {
            continue;
        }
        if !is_safe_archive_path(&raw_path) {
            return Err(conflict_error(format!(
                "refusing to extract suspicious archive path {:?} (absolute or contains ..)",
                raw_path.display()
            )));
        }
        // Reject everything except regular files and directories
        // before we touch the filesystem. An exported archive only
        // ever contains those two kinds, so symlink / hardlink / char
        // device / fifo entries can only come from a tampered or
        // hand-rolled archive trying to escape the staging dir.
        let entry_type = entry.header().entry_type();
        if !(entry_type.is_file() || entry_type.is_dir()) {
            return Err(conflict_error(format!(
                "refusing to extract tar entry {:?} of type {:?}; archives may contain only regular files and directories",
                raw_path.display(),
                entry_type,
            )));
        }
        let dest = staging_dir.join(&raw_path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent).with_context(|| format!("create parent {}", parent.display()))?;
        }
        if entry_type.is_dir() {
            std::fs::create_dir_all(&dest).with_context(|| format!("create directory entry {}", dest.display()))?;
            continue;
        }
        // Refuse to write through an existing symlink at `dest`.
        // `entry.unpack` calls `File::create`, which would follow a
        // pre-existing symlink left behind by a stale staging dir.
        if let Ok(meta) = std::fs::symlink_metadata(&dest) {
            if meta.file_type().is_symlink() {
                return Err(conflict_error(format!(
                    "refusing to write through pre-existing symlink at {}",
                    dest.display(),
                )));
            }
        }
        entry.unpack(&dest).with_context(|| format!("unpack tar entry to {}", dest.display()))?;
        // Final sanity check: the file we just wrote must be a regular
        // file, not a symlink the tar crate decided to honour.
        let meta =
            std::fs::symlink_metadata(&dest).with_context(|| format!("stat extracted entry {}", dest.display()))?;
        if !meta.file_type().is_file() {
            return Err(conflict_error(format!(
                "extracted entry at {} is not a regular file ({:?})",
                dest.display(),
                meta.file_type(),
            )));
        }
        if raw_path == Path::new(PRINCIPALS_ARCHIVE_PATH) {
            staged_principals = Some(dest);
        }
    }
    Ok(ExtractOutcome { staged_principals })
}

fn is_safe_archive_path(path: &Path) -> bool {
    if path.is_absolute() {
        return false;
    }
    for component in path.components() {
        match component {
            std::path::Component::Normal(_) => {}
            std::path::Component::CurDir => {}
            _ => return false,
        }
    }
    true
}

/// What `handle_principals_file` plans to do. Computed BEFORE the
/// live scope swap so we can fail early when the caller didn't
/// opt-in to RBAC changes, without leaving the scope half-restored.
enum PrincipalsPlan {
    NoStaged,
    NoChange,
    InstallNew,
    Overwrite,
}

/// Compute the principals action without mutating disk. Returns an
/// error when the planned action requires `--yes-overwrite-principals`
/// and the caller didn't pass it.
fn plan_principals_action(extract: &ExtractOutcome, allow_overwrite: bool) -> Result<PrincipalsPlan> {
    let Some(staged) = extract.staged_principals.as_ref() else {
        return Ok(PrincipalsPlan::NoStaged);
    };
    let target = principals_path();
    if !target.exists() {
        return Ok(PrincipalsPlan::InstallNew);
    }
    let existing =
        std::fs::read(&target).with_context(|| format!("read existing principals.yaml at {}", target.display()))?;
    let incoming =
        std::fs::read(staged).with_context(|| format!("read staged principals.yaml at {}", staged.display()))?;
    if existing == incoming {
        return Ok(PrincipalsPlan::NoChange);
    }
    if !allow_overwrite {
        return Err(conflict_error(format!(
            "archive principals.yaml differs from existing {} — re-run with --yes-overwrite-principals to replace RBAC config",
            target.display()
        )));
    }
    Ok(PrincipalsPlan::Overwrite)
}

/// Principals.yaml is the RBAC root-of-trust. It must NEVER be silently
/// overwritten, even when `--yes` accepts clobbering the scope dir.
/// Touching it requires a separate explicit opt-in
/// (`--yes-overwrite-principals`), which `plan_principals_action`
/// already validated.
fn apply_principals_action(extract: &ExtractOutcome, plan: PrincipalsPlan) -> Result<bool> {
    match plan {
        PrincipalsPlan::NoStaged | PrincipalsPlan::NoChange => Ok(false),
        PrincipalsPlan::InstallNew => {
            let Some(staged) = extract.staged_principals.as_ref() else {
                return Ok(false);
            };
            let target = principals_path();
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent)
                    .with_context(|| format!("create parent for principals.yaml at {}", parent.display()))?;
            }
            std::fs::copy(staged, &target)
                .with_context(|| format!("install principals.yaml at {}", target.display()))?;
            Ok(true)
        }
        PrincipalsPlan::Overwrite => {
            let Some(staged) = extract.staged_principals.as_ref() else {
                return Ok(false);
            };
            let target = principals_path();
            let backup = with_suffix(&target, &format!(".backup-{}", Utc::now().format("%Y%m%d%H%M%S")));
            std::fs::copy(&target, &backup)
                .with_context(|| format!("snapshot existing principals.yaml to {}", backup.display()))?;
            std::fs::copy(staged, &target)
                .with_context(|| format!("overwrite principals.yaml at {}", target.display()))?;
            Ok(true)
        }
    }
}

fn scope_dir_for(scope: &str) -> PathBuf {
    let home = dirs::home_dir().unwrap_or_else(|| PathBuf::from("."));
    home.join(".animus").join(scope)
}

fn animus_home() -> Result<PathBuf> {
    let home = dirs::home_dir().ok_or_else(|| anyhow!("could not resolve home directory for ~/.animus"))?;
    Ok(home.join(".animus"))
}

fn principals_path() -> PathBuf {
    protocol::Config::global_config_dir().join("principals.yaml")
}

fn default_export_path(scope: &str, exported_at: &chrono::DateTime<Utc>) -> PathBuf {
    let stamp = exported_at.format("%Y%m%d%H%M%S");
    PathBuf::from(format!("animus-state-{scope}-{stamp}.tar.zst"))
}

fn with_suffix(path: &Path, suffix: &str) -> PathBuf {
    let mut owned = path.as_os_str().to_owned();
    owned.push(suffix);
    PathBuf::from(owned)
}

fn scope_dir_is_nonempty(path: &Path) -> bool {
    match std::fs::read_dir(path) {
        Ok(mut it) => it.next().is_some(),
        Err(_) => false,
    }
}

/// Walk a staged scope payload looking for at least one regular file.
/// Returns `Ok(false)` for a tree of empty dirs, `Ok(true)` as soon as
/// any file is found, and propagates IO errors. Used as the swap-gate
/// guard — we never want to replace live state with a directory tree
/// that has no actual files.
fn staged_scope_contains_file(root: &Path) -> Result<bool> {
    let read = std::fs::read_dir(root).with_context(|| format!("read_dir {}", root.display()))?;
    for entry in read {
        let entry = entry.with_context(|| format!("read entry under {}", root.display()))?;
        let ft = entry.file_type().with_context(|| format!("stat {}", entry.path().display()))?;
        if ft.is_file() {
            return Ok(true);
        }
        if ft.is_dir() && staged_scope_contains_file(&entry.path())? {
            return Ok(true);
        }
    }
    Ok(false)
}

/// Names a freshly-created scope dir contains by default (markers,
/// origin pointers). If a scope dir only contains these, treat it as
/// empty for export-purposes — there is no real state to back up.
const SCOPE_BOOTSTRAP_FILENAMES: &[&str] = &[".project-root", ".git-origin"];

fn scope_dir_has_real_state(path: &Path) -> bool {
    match std::fs::read_dir(path) {
        Ok(read) => {
            for entry in read.flatten() {
                let name = entry.file_name().to_string_lossy().to_string();
                if !SCOPE_BOOTSTRAP_FILENAMES.contains(&name.as_str()) {
                    return true;
                }
            }
            false
        }
        Err(_) => false,
    }
}

/// Non-mutating scope-dir lookup. Prefers the hash-derived directory
/// when it exists, otherwise searches `~/.animus` for an existing
/// same-origin scope without writing markers (unlike
/// `protocol::scoped_state_root`, which would create files). Falls
/// back to the hash-derived path even if it does not yet exist; the
/// caller is responsible for refusing to act on a non-existent scope.
fn resolve_existing_scope_dir(project_root: &Path) -> (String, PathBuf) {
    let hash_name = repository_scope_for_path(project_root);
    let Some(home) = dirs::home_dir() else {
        return (hash_name.clone(), PathBuf::from(".animus").join(&hash_name));
    };
    let ao_root = home.join(".animus");
    let primary = ao_root.join(&hash_name);
    if primary.exists() {
        return (hash_name, primary);
    }
    if let Some(adopted) = find_adopted_scope_dir(&ao_root, project_root) {
        if let Some(name) = adopted.file_name().and_then(|n| n.to_str()).map(str::to_string) {
            return (name, adopted);
        }
    }
    (hash_name, primary)
}

fn find_adopted_scope_dir(ao_root: &Path, project_root: &Path) -> Option<PathBuf> {
    let origin = git_remote_origin(project_root)?;
    let canonical = project_root.canonicalize().unwrap_or_else(|_| project_root.to_path_buf());
    let entries = std::fs::read_dir(ao_root).ok()?;
    for entry in entries.flatten() {
        let scope_dir = entry.path();
        if !scope_dir.is_dir() {
            continue;
        }
        let Ok(existing_origin) = std::fs::read_to_string(scope_dir.join(".git-origin")) else {
            continue;
        };
        if existing_origin.trim() != origin {
            continue;
        }
        match std::fs::read_to_string(scope_dir.join(".project-root")) {
            Ok(existing_root) => {
                let recorded = Path::new(existing_root.trim());
                match recorded.canonicalize() {
                    Ok(existing_canonical) if existing_canonical == canonical => return Some(scope_dir),
                    Ok(_) => continue,
                    Err(_) => return Some(scope_dir),
                }
            }
            Err(_) => return Some(scope_dir),
        }
    }
    None
}

fn git_remote_origin(project_root: &Path) -> Option<String> {
    std::process::Command::new("git")
        .args(["remote", "get-url", "origin"])
        .current_dir(project_root)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::null())
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| !s.is_empty())
}

/// A scope id always comes from `repository_scope_for_path`, which
/// emits `<slug>-<12-hex>` with characters in `[a-z0-9-]`. Reject
/// anything else — we treat the scope name as a single path component
/// and don't want a crafted MANIFEST.json escaping `~/.animus`.
fn validate_scope_name(scope: &str) -> Result<()> {
    if scope.is_empty() {
        return Err(invalid_input_error(
            "exported state manifest is invalid: repo_scope is required — check MANIFEST.json in the archive",
        ));
    }
    for ch in scope.chars() {
        match ch {
            'a'..='z' | '0'..='9' | '-' => {}
            _ => {
                return Err(invalid_input_error(format!(
                    "manifest repo_scope {scope:?} contains illegal character {ch:?}; refusing import"
                )));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn touch(path: &Path, contents: &[u8]) {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        let mut f = File::create(path).unwrap();
        f.write_all(contents).unwrap();
    }

    fn lock_home(tmp: &Path) -> protocol::test_utils::EnvVarGuard {
        let guard = protocol::test_utils::EnvVarGuard::set("HOME", Some(tmp.to_string_lossy().as_ref()));
        let ao = tmp.join(".animus");
        std::fs::create_dir_all(&ao).unwrap();
        guard
    }

    fn fake_scope_state(scope_dir: &Path, with_runs: bool, with_artifacts: bool, with_secret: bool) {
        std::fs::create_dir_all(scope_dir).unwrap();
        touch(&scope_dir.join("config/state-machines.v1.json"), br#"{"states":["ready"]}"#);
        touch(&scope_dir.join("config/workflow-config.v2.json"), br#"{"workflows":[]}"#);
        touch(&scope_dir.join("daemon/pm-config.json"), br#"{"pool_size":4}"#);
        touch(&scope_dir.join("daemon/daemon.lock"), b"lock");
        touch(&scope_dir.join("daemon/daemon.log"), b"runtime log line");
        // Top-level scope state (load-bearing for restore).
        touch(&scope_dir.join("core-state.json"), br#"{"tasks":[]}"#);
        touch(&scope_dir.join("resume-config.json"), br#"{"resume":true}"#);
        touch(&scope_dir.join("workflow.db"), b"sqlite-fake");
        touch(&scope_dir.join("audit.jsonl"), b"{}\n");
        touch(&scope_dir.join("tasks-migrated.marker"), b"");
        touch(&scope_dir.join("state/agent-runtime-config.v2.json"), br#"{"agents":{}}"#);
        touch(&scope_dir.join("docs/architecture.json"), b"{}");
        touch(&scope_dir.join("metrics/pending.jsonl"), b"{}\n");
        touch(&scope_dir.join("logs/events.jsonl"), b"{}\n");
        // Top-level runtime junk that must be excluded.
        touch(&scope_dir.join("core-state.lock"), b"lock");
        touch(&scope_dir.join("control.sock"), b"socket-placeholder");
        // Bootstrap markers — `.project-root` carries an absolute
        // local path and `.git-origin` can embed credentials.
        touch(&scope_dir.join(".project-root"), b"/home/alice/project\n");
        touch(&scope_dir.join(".git-origin"), b"https://hunter2@github.com/me/repo.git\n");
        // Managed worktrees are excluded by default (potentially huge,
        // not portable across machines, and may contain unrelated
        // `.env` files in user checkouts).
        touch(&scope_dir.join("worktrees/task-123/.env"), b"SECRET=value\n");
        touch(&scope_dir.join("worktrees/task-123/src/lib.rs"), b"// code\n");
        if with_runs {
            touch(&scope_dir.join("runs/run-1/output.jsonl"), b"{}\n");
        }
        if with_artifacts {
            touch(&scope_dir.join("artifacts/blob.bin"), &[0u8; 32]);
        }
        if with_secret {
            touch(
                &scope_dir.join("config/oauth.json"),
                br#"{"linear_api_token":"sk-live-AAAABBBBCCCCDDDDEEEEFFFFGGGG"}"#,
            );
        }
        // Always include a cost-state file with `total_tokens` so we
        // also verify that ordinary numeric counters DON'T trip the
        // secret scan.
        touch(&scope_dir.join("cost-state.v1.json"), br#"{"total_tokens":12345,"runs":[]}"#);
    }

    #[test]
    fn export_creates_archive_with_manifest_and_default_scope_only() {
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let project_root = tmp.path().join("project");
        std::fs::create_dir_all(&project_root).unwrap();
        let scope = repository_scope_for_path(&project_root);
        let scope_dir = tmp.path().join(".animus").join(&scope);
        fake_scope_state(&scope_dir, true, true, false);
        let out_path = tmp.path().join("backup.tar.zst");

        handle_export(
            StateExportArgs {
                out: Some(out_path.to_string_lossy().to_string()),
                include_runs: false,
                include_artifacts: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .unwrap();

        assert!(out_path.exists(), "archive should be written");
        let manifest = read_manifest(&out_path).unwrap();
        assert_eq!(manifest.schema, EXPORT_SCHEMA_V1);
        assert_eq!(manifest.repo_scope, scope);
        assert!(!manifest.include_runs);
        assert!(!manifest.include_artifacts);

        // Confirm runs/artifacts were NOT pulled in.
        let names = archive_entries(&out_path);
        assert!(names.iter().any(|n| n == "scope/config/state-machines.v1.json"));
        assert!(names.iter().any(|n| n == "scope/daemon/pm-config.json"));
        // Top-level scope state must travel by default; the original
        // implementation missed these, leaving restores half-empty.
        assert!(names.iter().any(|n| n == "scope/core-state.json"), "core-state.json missing");
        assert!(names.iter().any(|n| n == "scope/resume-config.json"), "resume-config.json missing");
        assert!(names.iter().any(|n| n == "scope/workflow.db"), "workflow.db missing");
        assert!(names.iter().any(|n| n == "scope/audit.jsonl"), "audit.jsonl missing");
        assert!(names.iter().any(|n| n == "scope/tasks-migrated.marker"), "marker missing");
        assert!(names.iter().any(|n| n == "scope/state/agent-runtime-config.v2.json"), "state/ missing");
        assert!(names.iter().any(|n| n == "scope/docs/architecture.json"), "docs/ missing");
        assert!(names.iter().any(|n| n == "scope/metrics/pending.jsonl"), "metrics/ missing");
        assert!(names.iter().any(|n| n == "scope/logs/events.jsonl"), "logs/ missing");
        assert!(names.iter().any(|n| n == "scope/cost-state.v1.json"), "cost-state.v1.json missing");
        // Excludes.
        assert!(!names.iter().any(|n| n.starts_with("scope/runs/")), "runs excluded by default");
        assert!(!names.iter().any(|n| n.starts_with("scope/artifacts/")), "artifacts excluded by default");
        assert!(!names.iter().any(|n| n == "scope/daemon/daemon.lock"), "lock file is runtime-only");
        assert!(!names.iter().any(|n| n == "scope/daemon/daemon.log"), "log file is runtime-only");
        assert!(!names.iter().any(|n| n == "scope/core-state.lock"), "top-level lock excluded");
        assert!(!names.iter().any(|n| n == "scope/control.sock"), "control.sock excluded");
        assert!(!names.iter().any(|n| n.starts_with("scope/worktrees/")), "managed worktrees excluded by default");
        assert!(!names.iter().any(|n| n == "scope/.project-root"), ".project-root marker leaks local path");
        assert!(!names.iter().any(|n| n == "scope/.git-origin"), ".git-origin marker can leak credentials");
    }

    #[test]
    fn include_runs_pulls_runs_dir() {
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let project_root = tmp.path().join("project");
        std::fs::create_dir_all(&project_root).unwrap();
        let scope = repository_scope_for_path(&project_root);
        let scope_dir = tmp.path().join(".animus").join(&scope);
        fake_scope_state(&scope_dir, true, false, false);
        let out_path = tmp.path().join("with-runs.tar.zst");

        handle_export(
            StateExportArgs {
                out: Some(out_path.to_string_lossy().to_string()),
                include_runs: true,
                include_artifacts: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .unwrap();

        let names = archive_entries(&out_path);
        assert!(names.iter().any(|n| n == "scope/runs/run-1/output.jsonl"));
    }

    #[test]
    fn export_refuses_state_file_with_secret_key() {
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let project_root = tmp.path().join("project");
        std::fs::create_dir_all(&project_root).unwrap();
        let scope = repository_scope_for_path(&project_root);
        let scope_dir = tmp.path().join(".animus").join(&scope);
        fake_scope_state(&scope_dir, false, false, true);
        let out_path = tmp.path().join("rejected.tar.zst");

        let err = handle_export(
            StateExportArgs {
                out: Some(out_path.to_string_lossy().to_string()),
                include_runs: false,
                include_artifacts: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .expect_err("secret token should block export");
        let msg = err.to_string();
        assert!(msg.contains("linear_api_token") || msg.to_lowercase().contains("secret"), "got {msg}");
        assert!(!out_path.exists(), "no archive should be written on failure");
    }

    #[test]
    fn import_refuses_newer_schema_version() {
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let archive = tmp.path().join("future.tar.zst");
        let manifest = serde_json::json!({
            "schema": "animus.state.export.v9",
            "exported_at": "2030-01-01T00:00:00Z",
            "animus_version": "9.0.0",
            "repo_scope": "fake-scope-deadbeef",
            "include_runs": false,
            "include_artifacts": false,
            "file_count": 0,
            "total_bytes_uncompressed": 0
        });
        write_simple_archive(&archive, &serde_json::to_vec(&manifest).unwrap(), &[]);
        let project_root = tmp.path().join("project");
        std::fs::create_dir_all(&project_root).unwrap();
        let err = handle_import(
            StateImportArgs {
                archive: archive.to_string_lossy().to_string(),
                into_project: None,
                yes: true,
                yes_overwrite_principals: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .expect_err("newer schema should be rejected");
        assert!(err.to_string().contains("upgrade animus"), "got {err}");
    }

    #[test]
    fn import_refuses_when_target_nonempty_without_yes() {
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let project_root = tmp.path().join("project");
        std::fs::create_dir_all(&project_root).unwrap();
        let scope = repository_scope_for_path(&project_root);
        let scope_dir = tmp.path().join(".animus").join(&scope);
        fake_scope_state(&scope_dir, false, false, false);
        let out_path = tmp.path().join("backup.tar.zst");
        handle_export(
            StateExportArgs {
                out: Some(out_path.to_string_lossy().to_string()),
                include_runs: false,
                include_artifacts: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .unwrap();

        let err = handle_import(
            StateImportArgs {
                archive: out_path.to_string_lossy().to_string(),
                into_project: None,
                yes: false,
                yes_overwrite_principals: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .expect_err("non-empty target without --yes should fail");
        assert!(err.to_string().contains("--yes"), "got {err}");
    }

    #[test]
    fn import_takes_snapshot_and_swaps_with_yes() {
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let project_root = tmp.path().join("project");
        std::fs::create_dir_all(&project_root).unwrap();
        let scope = repository_scope_for_path(&project_root);
        let scope_dir = tmp.path().join(".animus").join(&scope);
        fake_scope_state(&scope_dir, false, false, false);
        let out_path = tmp.path().join("backup.tar.zst");
        handle_export(
            StateExportArgs {
                out: Some(out_path.to_string_lossy().to_string()),
                include_runs: false,
                include_artifacts: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .unwrap();

        // mutate the live scope so we can detect the snapshot captured the OLD contents.
        std::fs::write(scope_dir.join("config/state-machines.v1.json"), b"{\"mutated\":true}").unwrap();

        handle_import(
            StateImportArgs {
                archive: out_path.to_string_lossy().to_string(),
                into_project: None,
                yes: true,
                yes_overwrite_principals: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .unwrap();

        let ao_root = tmp.path().join(".animus");
        let mut snapshot = None;
        for entry in std::fs::read_dir(&ao_root).unwrap() {
            let entry = entry.unwrap();
            let name = entry.file_name().to_string_lossy().to_string();
            if name.starts_with(&format!("{scope}.backup-pre-import-")) {
                snapshot = Some(entry.path());
            }
        }
        let snapshot = snapshot.expect("snapshot dir created");
        let snap_state = std::fs::read(snapshot.join("config/state-machines.v1.json")).unwrap();
        assert_eq!(snap_state, b"{\"mutated\":true}", "snapshot should capture pre-import contents");
        let restored_state = std::fs::read(scope_dir.join("config/state-machines.v1.json")).unwrap();
        assert_eq!(restored_state, br#"{"states":["ready"]}"#, "live scope should now match the archive");
    }

    #[test]
    fn into_project_re_scopes_the_target() {
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let project_a = tmp.path().join("project-a");
        let project_b = tmp.path().join("project-b");
        std::fs::create_dir_all(&project_a).unwrap();
        std::fs::create_dir_all(&project_b).unwrap();
        let scope_a = repository_scope_for_path(&project_a);
        let scope_b = repository_scope_for_path(&project_b);
        assert_ne!(scope_a, scope_b);
        fake_scope_state(&tmp.path().join(".animus").join(&scope_a), false, false, false);

        let out_path = tmp.path().join("backup.tar.zst");
        handle_export(
            StateExportArgs {
                out: Some(out_path.to_string_lossy().to_string()),
                include_runs: false,
                include_artifacts: false,
            },
            project_a.to_str().unwrap(),
            true,
        )
        .unwrap();

        handle_import(
            StateImportArgs {
                archive: out_path.to_string_lossy().to_string(),
                into_project: Some(project_b.to_string_lossy().to_string()),
                yes: false,
                yes_overwrite_principals: false,
            },
            project_a.to_str().unwrap(),
            true,
        )
        .unwrap();

        let scope_b_dir = tmp.path().join(".animus").join(&scope_b);
        assert!(scope_b_dir.join("config/state-machines.v1.json").exists());
    }

    #[test]
    fn import_refuses_to_silently_overwrite_differing_principals_yaml() {
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let project_root = tmp.path().join("project");
        std::fs::create_dir_all(&project_root).unwrap();
        let scope = repository_scope_for_path(&project_root);
        let scope_dir = tmp.path().join(".animus").join(&scope);
        fake_scope_state(&scope_dir, false, false, false);
        // Write the SOURCE principals (the one that gets archived).
        let principals_path = tmp.path().join(".animus/principals.yaml");
        std::fs::write(&principals_path, b"principals:\n  - id: alice\n").unwrap();
        let out_path = tmp.path().join("backup.tar.zst");
        handle_export(
            StateExportArgs {
                out: Some(out_path.to_string_lossy().to_string()),
                include_runs: false,
                include_artifacts: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .unwrap();

        // Mutate the on-disk principals AND the on-disk scope state so
        // we can verify NEITHER is touched when import refuses.
        std::fs::write(&principals_path, b"principals:\n  - id: bob\n").unwrap();
        std::fs::write(scope_dir.join("core-state.json"), b"{\"mutated\":true}").unwrap();
        let err = handle_import(
            StateImportArgs {
                archive: out_path.to_string_lossy().to_string(),
                into_project: None,
                yes: true,
                yes_overwrite_principals: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .expect_err("differing principals.yaml without explicit opt-in should fail");
        assert!(err.to_string().contains("principals.yaml"), "got {err}");
        let after = std::fs::read(&principals_path).unwrap();
        assert_eq!(after, b"principals:\n  - id: bob\n", "principals.yaml must not be touched on refusal");
        let live_scope = std::fs::read(scope_dir.join("core-state.json")).unwrap();
        assert_eq!(
            live_scope, b"{\"mutated\":true}",
            "live scope must NOT be swapped when principals overwrite is refused"
        );
        let ao_root = tmp.path().join(".animus");
        for entry in std::fs::read_dir(&ao_root).unwrap().flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            assert!(!name.contains(".backup-pre-import-"), "no snapshot dir should be created when import is denied");
        }
    }

    #[test]
    fn import_refuses_to_move_live_scope_when_archive_has_no_scope_payload() {
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let project_root = tmp.path().join("project");
        std::fs::create_dir_all(&project_root).unwrap();
        let scope = repository_scope_for_path(&project_root);
        let scope_dir = tmp.path().join(".animus").join(&scope);
        fake_scope_state(&scope_dir, false, false, false);
        let archive = tmp.path().join("empty.tar.zst");
        let manifest = serde_json::json!({
            "schema": EXPORT_SCHEMA_V1,
            "exported_at": "2026-06-08T00:00:00Z",
            "animus_version": "0.5.8",
            "repo_scope": scope.clone(),
            "include_runs": false,
            "include_artifacts": false,
            "file_count": 0,
            "total_bytes_uncompressed": 0
        });
        // Manifest-only archive: no `scope/` payload at all.
        write_simple_archive(&archive, &serde_json::to_vec(&manifest).unwrap(), &[]);

        let pre_snapshot = std::fs::read(scope_dir.join("core-state.json")).unwrap();
        let err = handle_import(
            StateImportArgs {
                archive: archive.to_string_lossy().to_string(),
                into_project: None,
                yes: true,
                yes_overwrite_principals: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .expect_err("missing scope payload must be rejected");
        assert!(err.to_string().contains("scope"), "got {err}");
        let post = std::fs::read(scope_dir.join("core-state.json")).unwrap();
        assert_eq!(post, pre_snapshot, "live scope must NOT be moved on a corrupt archive");
    }

    #[test]
    fn import_refuses_empty_scope_payload() {
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let project_root = tmp.path().join("project");
        std::fs::create_dir_all(&project_root).unwrap();
        let scope = repository_scope_for_path(&project_root);
        let scope_dir = tmp.path().join(".animus").join(&scope);
        fake_scope_state(&scope_dir, false, false, false);
        let pre = std::fs::read(scope_dir.join("core-state.json")).unwrap();

        // Archive with a directory entry for `scope/` but no files
        // under it. Without the empty-scope guard, this would be
        // allowed to clobber the live scope.
        let archive = tmp.path().join("empty-scope.tar.zst");
        let manifest = serde_json::json!({
            "schema": EXPORT_SCHEMA_V1,
            "exported_at": "2026-06-08T00:00:00Z",
            "animus_version": "0.5.8",
            "repo_scope": scope.clone(),
            "include_runs": false,
            "include_artifacts": false,
            "file_count": 0,
            "total_bytes_uncompressed": 0,
        });
        let file = File::create(&archive).unwrap();
        let encoder = zstd::stream::write::Encoder::new(BufWriter::new(file), 1).unwrap().auto_finish();
        let mut builder = Builder::new(encoder);
        append_bytes(&mut builder, Path::new(MANIFEST_FILENAME), &serde_json::to_vec(&manifest).unwrap()).unwrap();
        let mut header = Header::new_gnu();
        header.set_path("scope/").unwrap();
        header.set_size(0);
        header.set_mode(0o755);
        header.set_entry_type(EntryType::Directory);
        header.set_cksum();
        builder.append(&header, std::io::empty()).unwrap();
        // Also include a NESTED empty dir under scope/ to exercise the
        // recursive file check — a one-level read_dir guard wouldn't
        // catch this.
        let mut header2 = Header::new_gnu();
        header2.set_path("scope/empty/").unwrap();
        header2.set_size(0);
        header2.set_mode(0o755);
        header2.set_entry_type(EntryType::Directory);
        header2.set_cksum();
        builder.append(&header2, std::io::empty()).unwrap();
        builder.finish().unwrap();
        drop(builder);

        let err = handle_import(
            StateImportArgs {
                archive: archive.to_string_lossy().to_string(),
                into_project: None,
                yes: true,
                yes_overwrite_principals: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .expect_err("empty scope/ payload must be rejected");
        let msg = err.to_string();
        assert!(msg.contains("empty") || msg.contains("no files"), "got {msg}");
        let post = std::fs::read(scope_dir.join("core-state.json")).unwrap();
        assert_eq!(post, pre, "live scope must remain intact");
    }

    #[test]
    fn export_allows_token_counter_in_state_files() {
        // Regression: `total_tokens: 12345` is a counter, not a secret.
        // The previous gate flagged any key containing "token" with a
        // non-empty value, blocking ordinary cost-state JSON exports.
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let project_root = tmp.path().join("project");
        std::fs::create_dir_all(&project_root).unwrap();
        let scope = repository_scope_for_path(&project_root);
        let scope_dir = tmp.path().join(".animus").join(&scope);
        fake_scope_state(&scope_dir, false, false, false);
        let out_path = tmp.path().join("with-cost-state.tar.zst");

        handle_export(
            StateExportArgs {
                out: Some(out_path.to_string_lossy().to_string()),
                include_runs: false,
                include_artifacts: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .expect("cost-state with numeric total_tokens should not be flagged");

        let names = archive_entries(&out_path);
        assert!(names.iter().any(|n| n == "scope/cost-state.v1.json"));
    }

    #[test]
    fn import_refuses_manifest_repo_scope_with_path_traversal() {
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let archive = tmp.path().join("evil.tar.zst");
        let manifest = serde_json::json!({
            "schema": EXPORT_SCHEMA_V1,
            "exported_at": "2026-06-08T00:00:00Z",
            "animus_version": "0.5.8",
            "repo_scope": "../escape",
            "include_runs": false,
            "include_artifacts": false,
            "file_count": 0,
            "total_bytes_uncompressed": 0,
        });
        write_simple_archive(
            &archive,
            &serde_json::to_vec(&manifest).unwrap(),
            &[(PathBuf::from(format!("{SCOPE_ARCHIVE_PREFIX}placeholder")), b"x".to_vec())],
        );
        let project_root = tmp.path().join("project");
        std::fs::create_dir_all(&project_root).unwrap();
        let err = handle_import(
            StateImportArgs {
                archive: archive.to_string_lossy().to_string(),
                into_project: None,
                yes: true,
                yes_overwrite_principals: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .expect_err("manifest scope with .. should be rejected");
        let msg = err.to_string();
        assert!(msg.contains("repo_scope") || msg.contains("illegal"), "got {msg}");
        // Nothing should have been created at the traversal target.
        let escape = tmp.path().join(".animus").join("..").join("escape");
        assert!(!escape.exists());
    }

    #[test]
    fn import_refuses_archive_with_symlink_entry() {
        let _lock = crate::test_env_lock().lock().unwrap_or_else(|p| p.into_inner());
        let tmp = tempdir().unwrap();
        let _home = lock_home(tmp.path());
        let project_root = tmp.path().join("project");
        std::fs::create_dir_all(&project_root).unwrap();
        let scope = repository_scope_for_path(&project_root);

        // Hand-craft a tar entry of type Symlink pointing at /etc/passwd
        // so the test doesn't depend on platform-specific symlink-honouring
        // by the tar crate's path-walking helpers.
        let archive = tmp.path().join("evil-symlink.tar.zst");
        let manifest = serde_json::json!({
            "schema": EXPORT_SCHEMA_V1,
            "exported_at": "2026-06-08T00:00:00Z",
            "animus_version": "0.5.8",
            "repo_scope": scope,
            "include_runs": false,
            "include_artifacts": false,
            "file_count": 1,
            "total_bytes_uncompressed": 0,
        });
        let file = File::create(&archive).unwrap();
        let encoder = zstd::stream::write::Encoder::new(BufWriter::new(file), 1).unwrap().auto_finish();
        let mut builder = Builder::new(encoder);
        let manifest_bytes = serde_json::to_vec(&manifest).unwrap();
        append_bytes(&mut builder, Path::new(MANIFEST_FILENAME), &manifest_bytes).unwrap();

        let mut header = Header::new_gnu();
        header.set_path("scope/core-state.json").unwrap();
        header.set_size(0);
        header.set_mode(0o777);
        header.set_entry_type(EntryType::Symlink);
        header.set_link_name("/etc/passwd").unwrap();
        header.set_cksum();
        builder.append(&header, std::io::empty()).unwrap();
        builder.finish().unwrap();
        drop(builder);

        let err = handle_import(
            StateImportArgs {
                archive: archive.to_string_lossy().to_string(),
                into_project: None,
                yes: true,
                yes_overwrite_principals: false,
            },
            project_root.to_str().unwrap(),
            true,
        )
        .expect_err("symlink tar entry should be rejected");
        // The rejection bubbles up through anyhow context; check the
        // full causal chain rather than just the top message.
        let chain: String = err.chain().map(|c| c.to_string()).collect::<Vec<_>>().join(" | ");
        assert!(
            chain.contains("regular files") || chain.contains("Symlink") || chain.contains("symlink"),
            "got {chain}"
        );
    }

    fn write_simple_archive(out: &Path, manifest_bytes: &[u8], entries: &[(PathBuf, Vec<u8>)]) {
        let file = File::create(out).unwrap();
        let encoder = zstd::stream::write::Encoder::new(BufWriter::new(file), 1).unwrap().auto_finish();
        let mut builder = Builder::new(encoder);
        append_bytes(&mut builder, Path::new(MANIFEST_FILENAME), manifest_bytes).unwrap();
        for (path, contents) in entries {
            append_bytes(&mut builder, path, contents).unwrap();
        }
        builder.finish().unwrap();
    }

    fn archive_entries(archive: &Path) -> Vec<String> {
        let file = File::open(archive).unwrap();
        let decoder = zstd::stream::read::Decoder::new(BufReader::new(file)).unwrap();
        let mut tar = Archive::new(decoder);
        tar.entries()
            .unwrap()
            .filter_map(Result::ok)
            .map(|e| e.path().unwrap().into_owned().to_string_lossy().to_string())
            .collect()
    }
}
